. ~/bin/dotfiles/zsh/env
. ~/bin/dotfiles/zsh/aliases
. ~/bin/dotfiles/zsh/prompt

# Plugins
plugins=(hub git osx ruby)

# Tmuxinator
[[ -s $HOME/.tmuxinator/scripts/tmuxinator ]] && source $HOME/.tmuxinator/scripts/tmuxinator

source ~/bin/tmuxinator.zsh

# nvm
source ~/.nvm/nvm.sh

PATH=$PATH:$HOME/tools/code/bin
PATH=$PATH:$HOME/tools/franklin/bin
PATH=$PATH:/Applications/Postgres93.app/Contents/MacOS/bin
# PATH=$PATH:/usr/local/Cellar/
# PATH=$PATH:/usr/local/Cellar/postgresql/9.3.1/bin
PATH=$PATH:/usr/local/bin/coffee
PATH=$PATH:$HOME/path-you-cloned-code-to/code/bin
export PATH