. ~/bin/dotfiles/zsh/env
. ~/bin/dotfiles/zsh/aliases
. ~/bin/dotfiles/zsh/prompt

# Plugins
plugins=(hub git osx ruby)

# Tmuxinator
[[ -s $HOME/.tmuxinator/scripts/tmuxinator ]] && source $HOME/.tmuxinator/scripts/tmuxinator

PATH=$PATH:/Applications/Postgres.app/Contents/Versions/latest/bin
PATH="./bin:$PATH"
PATH="$(brew --prefix)/bin:$PATH"
export PATH

source $HOME/bin/tmuxinator.zsh

# added by travis gem
[ -f /Users/joshsmith/.travis/travis.sh ] && source /Users/joshsmith/.travis/travis.sh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm

. $HOME/.asdf/asdf.sh

# append completions to fpath
fpath=(${ASDF_DIR}/completions $fpath)
# initialise completions with ZSH's compinit
autoload -Uz compinit && compinit

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
